<a href="https://colab.research.google.com/github/zihadbappy/bnfake/blob/main/Md_Gulazar_Hussain_of_CNN_with_ES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [196]:
!git clone https://github.com/zihadbappy/FakeDatasets.git

fatal: destination path 'FakeDatasets' already exists and is not an empty directory.


In [197]:
import pandas as pd
Dataset= pd.read_excel('/content/FakeDatasets/FinalData1.xlsx')

In [198]:
df= Dataset.filter(['Title','Statement', 'Class'], axis=1)

In [199]:
df.loc[(df.Class=='Real'),'Class']=1
df.loc[(df.Class=='Fake'),'Class']=0

In [200]:
df['Class']=df['Class'].astype('int')
df['Class'].dtypes

dtype('int64')

In [201]:
df.columns=['headline', 'content', 'label']

In [202]:
df.groupby('label').agg('count')

headline  content
label                   
0           993      993
1          1548     1548

In [203]:
df = df.drop_duplicates(subset='headline', keep="first")

In [204]:
df.groupby('label').agg('count')

headline  content
label                   
0           948      948
1          1545     1545

In [205]:
df.headline.duplicated().sum()

0

In [206]:
import re
from re import sub

In [207]:
def text_to_word_list(text):
    text = text.split()
    return text

def replace_strings(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\u00C0-\u017F"          #latin
                           u"\u2000-\u206F"          #generalPunctuations
                               
                           "]+", flags=re.UNICODE)
    english_pattern=re.compile('[a-zA-Z0-9]+', flags=re.I)
    #latin_pattern=re.compile('[A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s]*',)
    
    text=emoji_pattern.sub(r'', text)
    text=english_pattern.sub(r'', text)

    return text

def remove_punctuations(my_str):
    # define punctuation
    punctuations = '''````£|¢|Ñ+-*/=EROero৳০১২৩৪৫৬৭৮৯012–34567•89।!()-[]{};:'"“\’,<>./?@#$%^&*_~‘—॥”‰🤣⚽️✌�￰৷￰'''
    
    no_punct = ""
    for char in my_str:
        if char not in punctuations:
            no_punct = no_punct + char

    # display the unpunctuated string
    return no_punct



def joining(text):
    out=' '.join(text)
    return out

def preprocessing(text):
    out=remove_punctuations(replace_strings(text))
    return out

In [208]:
df['headline'] = df.headline.apply(lambda x: preprocessing(str(x)))
df['content'] = df.content.apply(lambda x: preprocessing(str(x)))

In [209]:
df['content'] = df['content'].str.replace(r'\n', ' ')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [210]:
df = df.reset_index(drop=True)

In [211]:
pip install bnlp_toolkit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [212]:
from bnlp import BasicTokenizer
from bnlp.corpus import stopwords, punctuations, letters, digits

btokenizer = BasicTokenizer()

word_list= []
def clean_text(text):
    tokens = btokenizer.tokenize(text)
    filtered = []
    for i in tokens:
        if i in stopwords:
            continue
    
        if i in punctuations + '‘' + '’':
            continue
    
        filtered.append(i)
        word_list.append(i)
    return " ".join(filtered)

# print("********** Before ***************")
# text = df.iloc[1]['content']
# print(text)
# print("\n********** After ***************")
# print(clean_text(text))

In [213]:
df['content'] = df.content.apply(clean_text)

In [214]:
df=df.dropna()
df

headline  \
0              এক দিনে করোনায় মৃত্যু  জনের নতুন শনাক্ত    
1                    কোভিডএর কাছে মানবজাতি হেরে গেল কেন   
2                                    সত্যিকারের ম্যাজিক   
3                                      এই সঙ্গনিরোধকালে   
4                              কী করছেন ঘরবন্দী লেখকেরা   
...                                                 ...   
2488  \nধারের টাকা না দেয়ায় জোরপূর্বক সোয়েটার পড়...   
2489         \nশেষ বয়সে পক্ষী মারা খেলেন শফিক রেহমান\n   
2490          \nরুনা লায়লার হাতে থাবড়া খেলেন ফেরদৌস\n   
2491  \nবাটে পেয়ে মুশফিককে সেদিন পিটিয়েছিলেন মুস্ত...   
2492  \nপ্রকাশ্যে কলা খাওয়া নিষিদ্ধ হচ্ছে মেয়েদের ...   

                                                content  label  
0     দেশে করোনাভাইরাসে আক্রান্ত হয়ে গত ঘণ্টায় মারা ...      1  
1     দ্বিতীয় বিশ্বযুদ্ধের বিশ্বের প্রভু হয়ে ওঠার প্...      1  
2     বাড়ির পাশেই ভিক্টোরিয়া পার্ক বিকেল ক্যানভাসারর...      1  
3     বাইরে বেরোচ্ছি কিছুদিন ভালো বেরোতে পারছি করোনা...      1  
4     লেখকেরাও ঘরবন্দী লেখকদের ঘরবন্দী সময় কেমন কাটছ...      1  
...                                                 ...    ...  
2488  রাজধানীতে ঘটলো আরেকটি চাঞ্চল্যকর হত্যাকান্ডের ...      0  
2489  অবশেষে বেরিয়ে এলো শফিক রেহমানের থলের বেড়াল স...      0  
2490  ছোটকাল ভক্ত জীবনে একটাই চাওয়া হাত গালে ছুঁয়ে...      0  
2491  বাটে মুশফিকুর রহিমকে মেরে হাত পা ভেঙ্গে দিলো ম...      0  
2492  প্রকাশ্যে কলা খাওয়া নিষিদ্ধ মেয়েদের রাস্তায়...      0  

[2493 rows x 3 columns]

# CNN

In [215]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from tensorflow.keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from tensorflow.keras.utils import to_categorical
from keras.callbacks import EarlyStopping
%matplotlib inline

In [216]:
X = df.content
Y = df.label
le = LabelEncoder()
Y = le.fit_transform(Y)
Y = Y.reshape(-1,1)

In [217]:
print(Y)

[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [218]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30, random_state=77,stratify=df['label'])

In [219]:
# fit a tokenizer
def create_tokenizer(lines):
	tokenizer = Tokenizer()
	tokenizer.fit_on_texts(lines)
	return tokenizer

In [220]:
  # calculate the maximum document length
def max_length(lines):
	return max([len(s.split()) for s in lines])

In [221]:
# calculate vocabulary size
# vocab_size = 86000

In [222]:
# encode a list of lines
def encode_text(tokenizer, lines, length):
	# integer encode
	encoded = tokenizer.texts_to_sequences(lines)
	# pad encoded sequences
	padded = pad_sequences(encoded, maxlen=length, padding='post')
	return padded

In [223]:

from pickle import load
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.vis_utils import plot_model
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Embedding
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.merge import concatenate
from keras.callbacks import EarlyStopping 

In [224]:
# define the model
def define_model(length, vocab_size):
	# channel 1
	inputs1 = Input(shape=(length,))
	embedding1 = Embedding(vocab_size, 100)(inputs1)
	conv1 = Conv1D(filters=32, kernel_size=4, activation='relu')(embedding1)
	drop1 = Dropout(0.5)(conv1)
	pool1 = MaxPooling1D(pool_size=2)(drop1)
	flat1 = Flatten()(pool1)
	# channel 2
	inputs2 = Input(shape=(length,))
	embedding2 = Embedding(vocab_size, 100)(inputs2)
	conv2 = Conv1D(filters=32, kernel_size=6, activation='relu')(embedding2)
	drop2 = Dropout(0.5)(conv2)
	pool2 = MaxPooling1D(pool_size=2)(drop2)
	flat2 = Flatten()(pool2)
	# channel 3
	inputs3 = Input(shape=(length,))
	embedding3 = Embedding(vocab_size, 100)(inputs3)
	conv3 = Conv1D(filters=32, kernel_size=8, activation='relu')(embedding3)
	drop3 = Dropout(0.5)(conv3)
	pool3 = MaxPooling1D(pool_size=2)(drop3)
	flat3 = Flatten()(pool3)
	# merge
	merged = concatenate([flat1, flat2, flat3])
	# interpretation
	dense1 = Dense(10, activation='relu')(merged)
	outputs = Dense(1, activation='sigmoid')(dense1)
	model = Model(inputs=[inputs1, inputs2, inputs3], outputs=outputs)
	# compile
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	# summarize
	print(model.summary())
	plot_model(model, show_shapes=True, to_file='multichannel.png')
	return model

In [225]:
tokenizer = create_tokenizer(X_train)
# calculate max document length
length = max_length(X_train)
# calculate vocabulary size
vocab_size = len(tokenizer.word_index) + 1
print('Max document length: %d' % length)
print('Vocabulary size: %d' % vocab_size)
# encode data
trainX = encode_text(tokenizer, X_train, length)
print(trainX.shape)
 
# define model
model = define_model(length, vocab_size)
# fit model
model.fit([trainX,trainX,trainX], array(Y_train), epochs=16, batch_size=32,
    callbacks=[EarlyStopping(monitor="accuracy",
    min_delta=0,
    patience=3,
    verbose=1,
    mode="auto",
    restore_best_weights=True,)])
# save the model
model.save('model.h5')

Max document length: 2174
Vocabulary size: 54320
(1745, 2174)
Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_16 (InputLayer)          [(None, 2174)]       0           []                               
                                                                                                  
 input_17 (InputLayer)          [(None, 2174)]       0           []                               
                                                                                                  
 input_18 (InputLayer)          [(None, 2174)]       0           []                               
                                                                                                  
 embedding_15 (Embedding)       (None, 2174, 100)    5432000     ['input_16[0][0]']               
                              

In [226]:
type(Y_test)

numpy.ndarray

In [227]:
loss, acc = model.evaluate([trainX,trainX,trainX], array(Y_train), verbose=0)
print('Train Accuracy: %f' % (acc*100))

testX = encode_text(tokenizer, X_test, length)

loss, acc = model.evaluate([testX,testX,testX],array(Y_test), verbose=0)
print('Test Accuracy: %f' % (acc*100))

Train Accuracy: 99.942696
Test Accuracy: 98.262030


In [228]:
testX

array([[ 4226, 12075,   987, ...,     0,     0,     0],
       [   88,    55,  1521, ...,     0,     0,     0],
       [ 1205,   161, 43524, ...,     0,     0,     0],
       ...,
       [  390,    68,  6200, ...,     0,     0,     0],
       [ 6125, 10218,   317, ...,     0,     0,     0],
       [   68,     5,     3, ...,     0,     0,     0]], dtype=int32)

In [229]:
trainX

array([[  213,  6109,  2587, ...,     0,     0,     0],
       [ 2771,    63, 26001, ...,     0,     0,     0],
       [   12,    77,  3363, ...,     0,     0,     0],
       ...,
       [  490,   781,  3532, ...,     0,     0,     0],
       [ 4197,  7363,    62, ...,     0,     0,     0],
       [   49,   129,  4298, ...,     0,     0,     0]], dtype=int32)

In [230]:
CNN_pred_y = model.predict([testX, testX, testX])

In [231]:
from sklearn.metrics import classification_report

In [232]:
classification_report(Y_test, np.around(CNN_pred_y), output_dict=True)

{'0': {'precision': 0.9656357388316151,
  'recall': 0.9894366197183099,
  'f1-score': 0.9773913043478261,
  'support': 284},
 '1': {'precision': 0.9934354485776805,
  'recall': 0.978448275862069,
  'f1-score': 0.9858849077090118,
  'support': 464},
 'accuracy': 0.982620320855615,
 'macro avg': {'precision': 0.9795355937046478,
  'recall': 0.9839424477901895,
  'f1-score': 0.9816381060284189,
  'support': 748},
 'weighted avg': {'precision': 0.9828804785671424,
  'recall': 0.982620320855615,
  'f1-score': 0.982660063652091,
  'support': 748}}

In [233]:
np.around(CNN_pred_y[20:25])

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [234]:
Y_test[20:25]

array([[0],
       [1],
       [1],
       [1],
       [0]])